<?php
# Created by Paul Flanders@HowToMoodle
# 11-04-2019 htm-1167
# File autogenerated < 040_buildConfig.php

unset($CFG);
global $CFG;
$CFG = new stdClass();
$CFG->dbtype    = 'mysqli';
$CFG->dblibrary = 'native';
$CFG->dbhost    = '<ip address>';
$CFG->dbname    = '<db name>';
$CFG->dbuser    = '<db user>';
$CFG->dbpass    = '<db password>';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = array (
        'dbpersist' => 0,
        'dbport' => '',
        'dbsocket' => '',
        'dbcollation' => 'utf8mb4_general_ci',);
$CFG->wwwroot   = 'https://<fqdn>';
$CFG->dataroot  = '<path to moodledata>';


require_once(__DIR__ . '/lib/setup.php');

